Feat/MB-73 - PUT and PATCH method - Update customers route
DenjiDev/makima-backoffice pull request #4
Opened 2023-07-01 20:20 UTC by EdisonMatos

Tenho uma nova PR para vocês revisarem:

- O que foi feito?
> Criada a rota de atualização de todos os clientes (customers) através dos métodos PUT (onde o dado informado é atualizado e os outros são zerados) e PATCH (onde o dado informado é atualizado e os outros permanecem inalterados).

Obs: Pra o método PUT funcionar como o desejado, no DTO dele tive que deixar os campos como opcionais, senão não seria possível informar apenas uma coisa ou outra que estivesse querendo alterar. Então essa é a explica pra eu ter deixado de "extender" as infos do create-customer-dto e ter informado toda a verificação no corpo da class do put.

Obs2: Em todos os testes chave "groups" está sendo ignorada porque quando ela é informada, retorna uns problemas que são provavelmente por não terem sido criados ainda.

Dúvida: Como eu movo a task no Jire pra "Code Review"? Deixei as tasks MB-71 E 73 como "doing" porque ainda não sei se está realmente finalizada.

Checklist:

- [x] Movi o card pra Code Review no Jira

- [x] Se tiver novas envs, adicionei elas no .env.example

- [-] Documentação necessária (swagger, testes e etc) - (Não peguei essa parte ainda)

[Card Jira - MB-73](https://makima-bot.atlassian.net/browse/MB-73)

2023-07-02 04:38 UTC, GabSnow24 requested changes

2023-07-02 04:38 UTC, GabSnow24 commented on src/customer/customer.controller.ts
> +  @ApiOperation({ summary: 'Update desired customers information and ignore all others'})
Só um método de update da entidade é suficiente, pode deixar só o put.

2023-07-02 04:38 UTC, GabSnow24 commented on src/customer/customer.controller.ts
> +  async partialUpdate(@Body() data: UpdatePatchCustomerDto, @Param('id') id: string) {
Pode remover o metódo patch, não é necessário

2023-07-02 04:38 UTC, GabSnow24 commented on src/customer/customer.service.ts
> +  async updateAllCustomerInfo(id: string, {email, name, phone, credit, groups}: UpdatePutCustomerDto) {
Não vamos utilizar um metódo pra atualizar todo a entidade ou apenas uma parte. Vamos ter um metódo que permita ambos, tanto a entidade toda ou apenas uma parte.

2023-07-02 04:38 UTC, GabSnow24 commented on src/customer/customer.service.ts
> +  async updateAnyCustomerInfo(id: string, data: UpdatePatchCustomerDto) {
Não vamos utilizar um metódo pra atualizar todo a entidade ou apenas uma parte. Vamos ter um metódo que permita ambos, tanto a entidade toda ou apenas uma parte.

2023-07-02 04:38 UTC, GabSnow24 commented on src/customer/customer.service.ts
> +    if (email === undefined) {
Essa implementação que vc fez de ifs não faz sentido em um método onde vc quer atualizar toda a entidade. Se vc quer atualizar todos os valores, pq ter valores que não estão sendo enviados? Se for ter um método para atualizar toda a entidade, todos os valores precisam ser enviados.

2023-07-02 04:38 UTC, GabSnow24 commented on src/customer/customer.service.ts
> +  async updateAllCustomerInfo(id: string, {email, name, phone, credit, groups}: UpdatePutCustomerDto) {
essa linha pode ser substituida por: 
`async updateAllCustomerInfo(id: string, data: UpdatePutCustomerDto) {`

2023-07-02 04:38 UTC, GabSnow24 commented on src/customer/customer.service.ts
> +
os ifs poderiam ser substituidos pelo código abaixo caso fosse necessário
`const { email = "", name = "", phone = "", credit = "" } =  data`

2023-07-02 04:38 UTC, GabSnow24 commented on src/customer/dto/create-customer.dto.ts
> +    @IsOptional()
O email nao é opcional na request

2023-07-03 18:06 UTC, GabSnow24 requested changes

2023-07-03 18:06 UTC, GabSnow24 commented on src/customer/customer.service.ts
> +    return this.prisma.customer.update({
Antes de atualizar, não seria melhor verificar se o usuário existe através do ID?

2023-07-03 18:06 UTC, GabSnow24 commented on package-lock.json
Estamos usando Yarn, o package-lock.json não deveria existir no projeto. O único arquivo de lock para dependências deveria ser o yarn.lock. Utilizar apenas o yarn para gerenciar pacotes.

2023-07-03 18:10 UTC, EdisonMatos commented on src/customer/customer.service.ts
> +    return this.prisma.customer.update({
Sim, sim. Vou providenciar essa verificação

2023-07-03 18:10 UTC, EdisonMatos commented on package-lock.json
Beleza.

2023-07-05 14:39 UTC, GabSnow24 requested changes

2023-07-05 14:39 UTC, GabSnow24 commented on src/customer/customer.service.ts
> +        throw new ConflictException(`Customer (${email}) already created`)
Não precisa retornar essa informação pro usuário.

2023-07-05 14:39 UTC, GabSnow24 commented on src/customer/customer.service.ts
> +  async findOne(id: string) {
O findOne já foi implementando pro @AllanVargens e já tá na develop. Puxa isso da Develop.

2023-07-05 14:39 UTC, GabSnow24 commented on src/customer/customer.service.ts
> +    return this.prisma.customer.update({
Pra dar mais legibilidade ao código, o interessante seria utilizar:
 `const foundCustomer = await this.findOne(id)`
 `if (!foundCustomer) {
        throw new NotFoundException(Customer (${id}) not found.)
    } `

2023-07-05 14:39 UTC, GabSnow24 commented on src/customer/customer.service.ts
> +    return this.prisma.customer.update({
e colocar a operação em um try catch, e em caso de erro, realizar um `Logger.error(error)` e fazer o throw do error

2023-07-06 22:54 UTC, GabSnow24 approved these changes

2023-07-07 00:18 UTC, merged